version: "3"

vars:

tasks:
  default:
    desc: Update cdn
    cmds:
      - task: update
  update:
    desc: Update cdn
    cmds:
      - git add .
      - git commit -m "update images"
      - git push


